In [8]:
import numpy as np

In [9]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[1:5]

array([1, 2, 3, 4])

In [11]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [6]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
slice_of_arr[:] # I am grabbing everything from that slice

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy[:] = 100  ## making changes the the arr_copy by broadcasting every value to be 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [20]:
arr  # Original array is still unaffected

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])