In [1]:
import numpy as np

In [42]:
my_list = [1,2,3]   # Creating a 1 dimensional array

In [43]:
arr = np.array(my_list)

In [44]:
arr

array([1, 2, 3])

In [45]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [46]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
np.arange(1, 21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [4]:
np.arange(0, 21, 2)  # Only want the even number

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.linspace(0, 5 , 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
np.linspace(0, 5 , 25)

array([0.        , 0.20833333, 0.41666667, 0.625     , 0.83333333,
       1.04166667, 1.25      , 1.45833333, 1.66666667, 1.875     ,
       2.08333333, 2.29166667, 2.5       , 2.70833333, 2.91666667,
       3.125     , 3.33333333, 3.54166667, 3.75      , 3.95833333,
       4.16666667, 4.375     , 4.58333333, 4.79166667, 5.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)   # 1 dimensional

array([0.24832334, 0.52227263, 0.30048171, 0.62411779, 0.68630741])

In [16]:
np.random.rand(5, 5)   # 2 dimensional

array([[0.49264226, 0.98964269, 0.90856508, 0.43044861, 0.15341315],
       [0.30510328, 0.11420092, 0.11398125, 0.72583996, 0.9901    ],
       [0.32079713, 0.18152051, 0.3849488 , 0.18913828, 0.30195885],
       [0.99032736, 0.60003352, 0.23972043, 0.74960196, 0.28973288],
       [0.61016879, 0.92659307, 0.52317175, 0.18032691, 0.86225855]])

In [19]:
np.random.randn(2)   # 1 dimensional

array([ 1.07528297, -0.92674004])

In [20]:
np.random.randn(5)

array([ 1.09487458,  1.20851486,  1.92633841, -0.26746859, -0.90583296])

In [21]:
np.random.randn(4,4 )   # 2 dimensional

array([[ 1.30533329, -1.70074917, -0.44411773, -1.60551579],
       [-1.97329304,  0.4543106 ,  1.32611637, -0.92988266],
       [-1.65843684, -0.15471465,  0.32269075, -1.00858734],
       [ 0.4936227 , -1.55730772,  0.32205587, -1.36102663]])

In [25]:
np.random.randint(1, 100)

58

In [26]:
np.random.randint(1, 100, 10)  # this will generate 10 random integers number

array([47, 85, 20, 37, 25,  4, 13, 37, 77, 18])

Creating an object arr

In [28]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Creating an obj name ranarr

In [30]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([ 5,  8, 18, 19, 46, 15,  1, 26, 26, 35])

In [31]:
arr.reshape(5, 5)  # reshaping the arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max()

46

In [33]:
ranarr.min()

1

If I want to know the index value of maximum element

In [34]:
ranarr.argmax()    # max number 46 is located in index 4

4

If I want to know the index value of minimum value

In [35]:
ranarr.argmin()  # min number ie 1 is located in index 6

6

In [37]:
arr.shape   # This will

(25,)

Now reshaping the original obj ie arr from 1 dimension to 2 dimension

In [39]:
arr = arr.reshape(5,5)

In [40]:
arr.shape

(5, 5)

In [47]:
from numpy.random import randint

In [48]:
randint(2,10)

6