In [1]:
import pandas as pd

data = {('January', 'Store A'): [100, 200, 150],
        ('February', 'Store A'): [120, 220, 180],
        ('January', 'Store B'): [90, 210, 160]}

df = pd.DataFrame(data, index=['Product A', 'Product B', 'Product C'])
print(df)

          January February January
          Store A  Store A Store B
Product A     100      120      90
Product B     200      220     210
Product C     150      180     160


In [2]:
import numpy as np

# 3D array with shape (3 products, 2 stores, 2 months)
data = np.array([[[100, 120], [90, 110]], 
                 [[200, 220], [210, 230]], 
                 [[150, 180], [160, 190]]])

print(data.shape)

(3, 2, 2)


In [3]:
print(data)

[[[100 120]
  [ 90 110]]

 [[200 220]
  [210 230]]

 [[150 180]
  [160 190]]]


In [ ]:
City     Day  Temperature  Humidity
New York  1       22°C         60%
New York  2       24°C         55%
London    1       18°C         70%
London    2       20°C         65%
Tokyo     1       26°C         50%
Tokyo     2       28°C         45%


In [4]:
data = np.array([
    [[22, 24], [60, 55]],   # New York
    [[18, 20], [70, 65]],   # London
    [[26, 28], [50, 45]]    # Tokyo
])

In [15]:
data[1][0]

array([18, 20])

In [16]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Math": [85, 78, 90],
    "English": [92, 88, 85]
}

df = pd.DataFrame(data)
print(df)

      Name  Math  English
0    Alice    85       92
1      Bob    78       88
2  Charlie    90       85
